const { Client, LocalAuth, MessageMedia } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');
const QRCode = require('qrcode');
const axios = require('axios');
const http = require('http');
const fs = require('fs');
const path = require('path');

const FLASK_URL = 'http://127.0.0.1:5000/greenapi';
const BRIDGE_PORT = 5001;

console.log('🚀 Initializing Native WhatsApp Web Bridge...');

const client = new Client({
    authStrategy: new LocalAuth({ dataPath: './.wwebjs_auth' }),
    webVersionCache: {
        type: 'remote',
        remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1014717897-alpha.html',
    },
    puppeteer: {
        headless: process.env.PUPPETEER_HEADLESS === 'false' ? false : true,
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-gpu',
            '--disable-extensions',
            '--no-first-run',
            '--no-zygote',
            '--single-process',
            '--disable-accelerated-2d-canvas',
            '--js-flags="--max-old-space-size=180"',
            '--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
        ]
    }
});

let currentPairingCode = null;
let isQrReady = false;

client.on('qr', async (qr) => {
    isQrReady = true;
    console.log('\n==================================================');
    console.log('📱 FRESH NATIVE WHATSAPP WEB ENGINE INITIALIZED!');
    console.log('==================================================\n');

    try {
        if (!client.info && !currentPairingCode) {
            try {
                currentPairingCode = await client.requestPairingCode('916305970096');
                console.log(`🔑 [Native WA 8-Digit Pairing Code Generated] -> ${currentPairingCode}`);
            } catch (pErr) {
                console.log(`[Pairing Code Auto-gen note]: ${pErr.message}`);
            }
        }

        const qrPath = path.join(__dirname, 'static', 'qr.png');
        if (!fs.existsSync(path.dirname(qrPath))) {
            fs.mkdirSync(path.dirname(qrPath), { recursive: true });
        }
        await QRCode.toFile(qrPath, qr, { width: 500, margin: 2 });
        console.log(`[Native WA QR Image Saved] -> ${qrPath}`);
    } catch (err) {
        console.error('[Native WA QR Export Error]:', err.message);
    }
});

client.on('ready', () => {
    console.log('\n✅ Native WhatsApp Web Bridge Connected & Ready!');
    console.log(`👤 Logged in user ID: ${client.info.wid._serialized}`);
});

client.on('authenticated', () => {
    console.log('🔑 WhatsApp Web session authenticated successfully!');
});

client.on('auth_failure', (msg) => {
    console.error('❌ WhatsApp Web auth failure:', msg);
});

const processedMsgIds = new Set();

async function handleIncomingMessage(msg) {
    try {
        // If outbound reply generated by bot itself, skip to prevent feedback loops
        if (msg.fromMe && (msg.body.includes('Email Draft Ready') || msg.body.includes('Email sent successfully') || msg.body.includes('Connect Another'))) {
            return;
        }

        const msgId = msg.id ? msg.id.id : null;
        if (msgId) {
            if (processedMsgIds.has(msgId)) {
                return;
            }
            processedMsgIds.add(msgId);
            if (processedMsgIds.size > 1000) {
                const firstItem = processedMsgIds.values().next().value;
                processedMsgIds.delete(firstItem);
            }
        }

        const from = msg.from;
        const body = msg.body || '';
        let mediaUrl = null;
        let fileName = null;

        console.log(`[Native WA Incoming] From: ${from} | Body: '${body.substring(0, 50)}...' | HasMedia: ${msg.hasMedia}`);

        if (msg.hasMedia) {
            try {
                const media = await msg.downloadMedia();
                if (media && media.data) {
                    const ext = media.mimetype.split('/')[1]?.split(';')[0] || 'bin';
                    fileName = media.filename || `doc_${Date.now()}.${ext}`;
                    const savePath = path.join(__dirname, 'static', 'uploads', fileName);
                    
                    if (!fs.existsSync(path.dirname(savePath))) {
                        fs.mkdirSync(path.dirname(savePath), { recursive: true });
                    }
                    
                    fs.writeFileSync(savePath, Buffer.from(media.data, 'base64'));
                    mediaUrl = `http://127.0.0.1:5000/static/uploads/${fileName}`;
                    console.log(`[Native WA Media Saved] -> ${savePath}`);
                }
            } catch (mediaErr) {
                console.error('[Native WA Media Error]:', mediaErr.message);
            }
        }

        const payload = {
            typeWebhook: 'incomingMessageReceived',
            senderData: {
                sender: from,
                chatId: from
            },
            messageData: {
                typeMessage: msg.hasMedia ? 'documentMessage' : 'textMessage',
                textMessageData: {
                    textMessage: body
                },
                documentMessageData: mediaUrl ? {
                    downloadUrl: mediaUrl,
                    fileName: fileName,
                    caption: body
                } : null
            }
        };

        await axios.post(FLASK_URL, payload, { timeout: 10000 });
        console.log(`[Native WA Webhook Forwarded] -> Flask 200 OK`);
    } catch (err) {
        console.error('[Native WA Processing Error]:', err.message);
    }
}

client.on('message', handleIncomingMessage);
client.on('message_create', handleIncomingMessage);

// Outbound Message HTTP Server on Port 5001
const server = http.createServer(async (req, res) => {
    if (req.method === 'GET' && req.url.startsWith('/pair-code')) {
        try {
            if (client.info && client.info.wid) {
                console.log(`[Native WA Status] Client is ALREADY connected as ${client.info.wid._serialized}!`);
                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({
                    status: 'already_connected',
                    pairingCode: 'CONNECTED',
                    message: `WhatsApp is ALREADY linked & active for ${client.info.wid.user}!`
                }));
                return;
            }

            const urlObj = new URL(req.url, 'http://127.0.0.1:5001');
            const rawPhone = urlObj.searchParams.get('phone') || '916305970096';
            const cleanPhone = rawPhone.replace('+', '').replace(/\s+/g, '');
            const forceNew = urlObj.searchParams.get('force') === 'true';

            let code = null;
            if (!forceNew && currentPairingCode) {
                code = currentPairingCode;
                console.log(`[Pairing Code Cached] Returning active code: ${code}`);
            } else {
                console.log(`[Pairing Code Request] Requesting fresh code for ${cleanPhone}...`);
                try {
                    code = await client.requestPairingCode(cleanPhone);
                    currentPairingCode = code;
                } catch (pErr) {
                    if (currentPairingCode) {
                        code = currentPairingCode;
                    } else {
                        throw pErr;
                    }
                }
            }

            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ status: 'success', pairingCode: code, phone: cleanPhone }));
        } catch (err) {
            console.error('[Pairing Code Error]:', err.message);
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: err.message, pairingCode: currentPairingCode || 'RETRY_IN_5S', status: 'error' }));
        }
        return;
    }

    if (req.method === 'POST' && req.url === '/send') {
        let bodyStr = '';
        req.on('data', chunk => { bodyStr += chunk; });
        req.on('end', async () => {
            try {
                const data = JSON.parse(bodyStr);
                const toPhone = (data.to || '').replace('+', '').replace('whatsapp:', '').replace(/\s+/g, '');
                const text = data.message || '';

                if (!toPhone || !text) {
                    res.writeHead(400, { 'Content-Type': 'application/json' });
                    res.end(JSON.stringify({ error: 'Missing to or message' }));
                    return;
                }

                const chatId = (toPhone.includes('@c.us') || toPhone.includes('@lid') || toPhone.includes('@g.us')) ? toPhone : `${toPhone}@c.us`;
                console.log(`[Native WA Outbound] Sending to ${chatId}...`);
                
                await client.sendMessage(chatId, text);
                console.log(`[Native WA Outbound Success] Delivered to ${chatId}`);

                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ status: 'sent', chatId: chatId }));
            } catch (err) {
                console.error('[Native WA Outbound Error]:', err.message);
                res.writeHead(500, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ error: err.message }));
            }
        });
    } else {
        res.writeHead(404, { 'Content-Type': 'text/plain' });
        res.end('Not Found');
    }
});

server.listen(BRIDGE_PORT, '127.0.0.1', () => {
    console.log(`📡 Native WhatsApp Outbound Bridge listening on http://127.0.0.1:${BRIDGE_PORT}`);
});

client.initialize();
